services:
  kafka1:
    container_name: kafka1
    build:
      context: container_images/kafka/.
      dockerfile: Dockerfile
    ports:
      - '19092:19092'
      - '7071:7071'
    volumes:
      - ./config/kafka1/server.properties:/opt/kafka/config/server.properties
      - ./config/kafka1/kafka-metrics.yml:/opt/jmx_exporter/kafka-metrics.yml
      - ./logs/kafka_data/kafka1/:/data/kafka/
      - ./logs/kafka_data/kafka1:/opt/kafka/logs
    networks:
      dahbest:
        ipv4_address: 172.80.0.11

  kafka2:
    container_name: kafka2
    build:
      context: container_images/kafka/.
      dockerfile: Dockerfile
    ports:
      - '29092:29092'
      - '7072:7071'
    volumes:
      - ./config/kafka2/server.properties:/opt/kafka/config/server.properties
      - ./config/kafka2/kafka-metrics.yml:/opt/jmx_exporter/kafka-metrics.yml
      - ./logs/kafka_data/kafka2/:/data/kafka/
      - ./logs/kafka_data/kafka1:/opt/kafka/logs
    networks:
      dahbest:
        ipv4_address: 172.80.0.12

  kafka3:
    container_name: kafka3
    build:
      context: container_images/kafka/.
      dockerfile: Dockerfile
    ports:
      - '39092:39092'
      - '7073:7071'
    volumes:
      - ./config/kafka3/server.properties:/opt/kafka/config/server.properties
      - ./logs/kafka_data/kafka3/:/data/kafka/
      - ./logs/kafka_data/kafka1:/opt/kafka/logs
    networks:
      dahbest:
        ipv4_address: 172.80.0.13

  kafka-ui:
    container_name: kafka-ui
    build:
      context: container_images/provectus/.
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./config/provectus/config.yml:/opt/config.yml
    networks:
      dahbest:
        ipv4_address: 172.80.0.16
    depends_on:
      - kafka1
      - kafka2
      - kafka3

  kafka-julie:
    container_name: kafka-julie
    build:
      context: ./container_images/kafka-julie
      dockerfile: Dockerfile
    environment:
      github_username: ${github_username}
      github_email: ${github_email}
      github_repo: ${github_repo}
      github_token: ${github_token}
      ngrok_token: ${ngrok_token}
    volumes:
      - ./config/kafka-julie/julie.properties:/opt/kafka_julie/config/julie.properties
      - ./config/kafka-julie/ngrok.yml.template:/opt/ngrok_tunnel/ngrok.yml.template
      - ./logs/julie:/opt/kafka_julie/logs
      - ./logs/ngrok:/opt/ngrok_tunnel/logs
    ports:
      - 8090:8090
      - 4040:4040
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    stdin_open: true
    tty: true
    networks:
      dahbest:
        ipv4_address: 172.80.0.60

  team-a:
    container_name: team-a
    build:
      context: ./container_images/team-a
      dockerfile: Dockerfile
    stdin_open: true
    tty: true   
    volumes:
      - ./config/team-a/configs:/mnt/configs
      - ./config/team-a/topologies:/mnt/topologies
    networks:
      dahbest:
        ipv4_address: 172.80.0.65

networks:
  dahbest:
    external: true
