services:
  kafka1:
    container_name: kafka1
    image: mucagriaktas/kafka:3.8.0
    environment:
      - node_id=1
      - hostname=kafka1
      - KAFKA_CLUSTER_MEMBERS=1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
      - EXTERNAL_PORT=19092
    ports:
      - '19092:19092'
    networks:
      dahbest:
        ipv4_address: 172.80.0.11

  kafka2:
    container_name: kafka2
    image: mucagriaktas/kafka:3.8.0
    environment:
      - node_id=2
      - hostname=kafka2
      - KAFKA_CLUSTER_MEMBERS=1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
      - EXTERNAL_PORT=29092
    ports:
      - '29092:29092'
    networks:
      dahbest:
        ipv4_address: 172.80.0.12

  kafka3:
    container_name: kafka3
    image: mucagriaktas/kafka:3.8.0
    environment:
      - node_id=3
      - hostname=kafka3
      - KAFKA_CLUSTER_MEMBERS=1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
      - EXTERNAL_PORT=39092
    ports:
      - '39092:39092'
    networks:
      dahbest:
        ipv4_address: 172.80.0.13

networks:
  dahbest:
    external: true