services:
  kafka1:
    build:
      context: ./container_image
      dockerfile: Dockerfile
    container_name: kafka1
    stdin_open: true
    tty: true   
    volumes:
      - ./kafka1:/mnt/config
    command: /bin/bash
    networks:
      dahbest:
        ipv4_address: 172.80.0.10

  zookeeper1:
    build:
      context: ./container_image
      dockerfile: Dockerfile
    container_name: zookeeper1
    stdin_open: true
    tty: true   
    volumes:
      - ./zookeeper1:/mnt/config
      - ./zookeeper1/zookeeper_3_7_2/zoo.cfg:/mnt/apache-zookeeper-3.7.2-bin/conf/zoo.cfg
    command: /bin/bash
    networks:
      dahbest:
        ipv4_address: 172.80.0.11

  kafka2:
    build:
      context: ./container_image
      dockerfile: Dockerfile
    container_name: kafka2
    stdin_open: true
    tty: true   
    volumes:
      - ./kafka2:/mnt/config
    command: /bin/bash
    networks:
      dahbest:
        ipv4_address: 172.80.0.12

  zookeeper2:
    build:
      context: ./container_image
      dockerfile: Dockerfile
    container_name: zookeeper2
    stdin_open: true
    tty: true   
    volumes:
      - ./zookeeper2:/mnt/config
      - ./zookeeper2/zookeeper_3_7_2/zoo.cfg:/mnt/apache-zookeeper-3.7.2-bin/conf/zoo.cfg
    command: /bin/bash
    networks:
      dahbest:
        ipv4_address: 172.80.0.13

  kafka3:
    build:
      context: ./container_image
      dockerfile: Dockerfile
    container_name: kafka3
    stdin_open: true
    tty: true   
    volumes:
      - ./kafka3:/mnt/config
    command: /bin/bash
    networks:
      dahbest:
        ipv4_address: 172.80.0.14

  zookeeper3:
    build:
      context: ./container_image
      dockerfile: Dockerfile
    container_name: zookeeper3
    stdin_open: true
    tty: true   
    volumes:
      - ./zookeeper3:/mnt/config
      - ./zookeeper3/zookeeper_3_7_2/zoo.cfg:/mnt/apache-zookeeper-3.7.2-bin/conf/zoo.cfg
    command: /bin/bash
    networks:
      dahbest:
        ipv4_address: 172.80.0.15

networks:
  dahbest: 
    external: true