lowercaseOutputName: true
lowercaseOutputLabelNames: true

rules:
  # Generic JVM metrics
  - pattern: "java.lang<type=OperatingSystem>([^:]+):"
    name: kafka_os_$1
    type: GAUGE

  # Memory metrics
  - pattern: "java.lang<type=Memory>HeapMemoryUsage"
    name: kafka_memory_heap
    type: GAUGE

  # Kafka specific metrics
  - pattern: "kafka.server<type=(.+), name=(.+)><>Value"
    name: kafka_server_$1_$2
    type: GAUGE
    
  - pattern: "kafka.controller<type=(.+), name=(.+)><>Value"
    name: kafka_controller_$1_$2
    type: GAUGE
    
  - pattern: "kafka.network<type=(.+), name=(.+)><>Value"
    name: kafka_network_$1_$2
    type: GAUGE
    
  - pattern: "kafka.log<type=(.+), name=(.+)><>Value"
    name: kafka_log_$1_$2
    type: GAUGE

  # Topic and partition metrics
  - pattern: "kafka.server<type=BrokerTopicMetrics, name=(.+)><>Count"
    name: kafka_server_brokertopicmetrics_$1_total
    type: COUNTER

  # Replica manager metrics
  - pattern: "kafka.server<type=ReplicaManager, name=(.+)><>Value"
    name: kafka_server_replicamanager_$1
    type: GAUGE