services:
  redhat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kafka
    stdin_open: true
    tty: true   
    volumes:
      - ./home:/mnt/config
    command: /bin/bash