kafka:
  clusters:
    - name: cagri_cluster
      bootstrapServers: kafka1:9092,kafka2:9092,kafka3:9092
      schemaRegistry: http://kafka-schema-registry:18081
      
server:
  port: 8080

logging:
  level:
    root: INFO