services:
  broker1:
    container_name: broker1
    hostname: broker1
    build:
      context: ./images/kafka/broker/.
      dockerfile: Dockerfile
    ports:
      - '19092:19092'
    volumes:
      - ./configs/kafka/broker1/broker.properties:/opt/kafka/config/broker.properties
      - ./configs/kafka/broker1/broker_server_jaas.conf:/opt/kafka/config/broker_server_jaas.conf
      - ./configs/kafka/broker1/admin_client.conf:/opt/kafka/config/admin_client.conf
      - ./configs/kafka/broker1/jks/:/opt/kafka/config/jks/
      - ./logs/kafka/broker1/data/:/opt/data/
      - ./logs/kafka/broker1/logs/:/opt/kafka/logs/
    networks:
      dahbest:
        ipv4_address: 172.80.0.11
    extra_hosts:
      - "broker1:172.80.0.11"
      - "broker2:172.80.0.12"
      - "broker3:172.80.0.13"
      - "controller1:172.80.0.21"
      - "kafka-ui:172.80.0.17"
      - "localhost:172.80.0.1"

  broker2:
    container_name: broker2
    hostname: broker2
    build:
      context: ./images/kafka/broker/.
      dockerfile: Dockerfile
    ports:
      - '29092:29092'
    volumes:
      - ./configs/kafka/broker2/broker.properties:/opt/kafka/config/broker.properties
      - ./configs/kafka/broker2/broker_server_jaas.conf:/opt/kafka/config/broker_server_jaas.conf
      - ./configs/kafka/broker2/admin_client.conf:/opt/kafka/config/admin_client.conf
      - ./configs/kafka/broker2/jks/:/opt/kafka/config/jks/
      - ./logs/kafka/broker2/data/:/opt/data/
      - ./logs/kafka/broker2/logs/:/opt/kafka/logs/
    networks:
      dahbest:
        ipv4_address: 172.80.0.12
    extra_hosts:
      - "broker1:172.80.0.11"
      - "broker2:172.80.0.12"
      - "broker3:172.80.0.13"
      - "controller1:172.80.0.21"
      - "kafka-ui:172.80.0.17"
      - "localhost:172.80.0.1"

  broker3:
    container_name: broker3
    hostname: broker3
    build:
      context: ./images/kafka/broker/.
      dockerfile: Dockerfile
    ports:
      - '39092:39092'
    volumes:
      - ./configs/kafka/broker3/broker.properties:/opt/kafka/config/broker.properties
      - ./configs/kafka/broker3/broker_server_jaas.conf:/opt/kafka/config/broker_server_jaas.conf
      - ./configs/kafka/broker3/admin_client.conf:/opt/kafka/config/admin_client.conf
      - ./configs/kafka/broker3/jks/:/opt/kafka/config/jks/
      - ./logs/kafka/broker3/data/:/opt/data/
      - ./logs/kafka/broker3/logs/:/opt/kafka/logs/
    networks:
      dahbest:
        ipv4_address: 172.80.0.13
    extra_hosts:
      - "broker1:172.80.0.11"
      - "broker2:172.80.0.12"
      - "broker3:172.80.0.13"
      - "controller1:172.80.0.21"
      - "kafka-ui:172.80.0.17"
      - "localhost:172.80.0.1"

  controller1:
    container_name: controller1
    hostname: controller1
    build:
      context: ./images/kafka/controller/.
      dockerfile: Dockerfile
    volumes:
      - ./configs/kafka/controller1/controller.properties:/opt/kafka/config/controller.properties
      - ./configs/kafka/controller1/controller_server_jaas.conf:/opt/kafka/config/controller_server_jaas.conf
      - ./configs/kafka/controller1/admin_client.conf:/opt/kafka/config/admin_client.conf
      - ./configs/kafka/controller1/jks/:/opt/kafka/config/jks/
      - ./logs/kafka/controller1/data/:/opt/data/
      - ./logs/kafka/controller1/logs/:/opt/kafka/logs/
    networks:
      dahbest:
        ipv4_address: 172.80.0.21
    extra_hosts:
      - "broker1:172.80.0.11"
      - "broker2:172.80.0.12"
      - "broker3:172.80.0.13"
      - "controller1:172.80.0.21"

  kafka-ui:
    container_name: kafka-ui
    build:
      context: ./images/provectus/.
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./configs/provectus/config.yml:/opt/config.yml
      - ./configs/provectus/jks/:/opt/jks/
    networks:
      dahbest:
        ipv4_address: 172.80.0.17
    depends_on:
      - broker1
      - controller1
    extra_hosts:
      - "broker1:172.80.0.11"
      - "broker2:172.80.0.12"
      - "broker3:172.80.0.13"
      - "kafka-ui:172.80.0.17"

networks:
  dahbest:
    external: true