services:
  kafka1:
    container_name: kafka1
    hostname: kafka1
    build:
      context: ./images/kafka/.
      dockerfile: Dockerfile
    ports:
      - '19092:19092'
    volumes:
      - ./configs/kafka/kafka1/server.properties:/opt/kafka/config/server.properties
      - ./logs/kafka/kafka1/data/:/opt/data/
      - ./logs/kafka/kafka1/logs/:/opt/kafka/logs/
    networks:
      dahbest:
        ipv4_address: 172.80.0.11

  kafka2:
    container_name: kafka2
    hostname: kafka2
    build:
      context: ./images/kafka/.
      dockerfile: Dockerfile
    ports:
      - '29092:29092'
    volumes:
      - ./configs/kafka/kafka2/server.properties:/opt/kafka/config/server.properties
      - ./logs/kafka/kafka2/data:/opt/data/
      - ./logs/kafka/kafka2/logs/:/opt/kafka/logs/
    networks:
      dahbest:
        ipv4_address: 172.80.0.12

  kafka3:
    container_name: kafka3
    hostname: kafka3
    build:
      context: ./images/kafka/.
      dockerfile: Dockerfile
    ports:
      - '39092:39092'
    volumes:
      - ./configs/kafka/kafka3/server.properties:/opt/kafka/config/server.properties
      - ./logs/kafka/kafka3/data:/opt/data/
      - ./logs/kafka/kafka3/logs/:/opt/kafka/logs/
    networks:
      dahbest:
        ipv4_address: 172.80.0.13

  debezium:
    hostname: debezium
    container_name: debezium
    build:
      context: ./images/debezium
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
      - "8084:8080"
    volumes:
      - ./configs/debezium/connect-distributed.properties:/opt/kafka/config/connect-distributed.properties
      - ./configs/debezium/connect-metrics.yml:/opt/jmx_exporter/connect-metrics.yml
      - ./logs/debezium:/data/kafka-connect
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - postgres
    networks:
      dahbest:
        ipv4_address: 172.80.0.15

  kafka-ui:
    container_name: kafka-ui
    build:
      context: ./images/provectus/.
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./configs/provectus/config.yml:/opt/kafka-ui/config.yml
    networks:
      dahbest:
        ipv4_address: 172.80.0.16
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      
  postgres:
      image: postgres:16
      container_name: postgres
      environment:
        POSTGRES_USER: cagri
        POSTGRES_PASSWORD: 3541
        POSTGRES_DB: postgres
      ports:
        - "5432:5432"
      volumes:
        - ./logs/postgres/:/var/lib/postgresql/data
      networks:
        dahbest:
          ipv4_address: 172.80.0.20
      command: ["postgres", "-c", "wal_level=logical", "-c", "max_wal_senders=10", "-c", "max_replication_slots=10"]   
         
networks:
  dahbest:
    external: true