services:
  kafka1:
    container_name: kafka1
    build:
      context: ./images/kafka/.
      dockerfile: Dockerfile
    ports:
      - '19092:19092'
      - '7071:7071'
    volumes:
      - ./config/kafka1/server.properties:/opt/kafka/config/server.properties
      - ./config/kafka1/kafka-metrics.yml:/opt/jmx_exporter/kafka-metrics.yml
      - ./logs/kafka_data/kafka1/:/opt/kafka/logs
      - ./logs/kafka_data/kafka1/metadata/:/data/kafka
    networks:
      dahbest:
        ipv4_address: 172.80.0.11

  kafka2:
    container_name: kafka2
    build:
      context: ./images/kafka/.
      dockerfile: Dockerfile
    ports:
      - '29092:29092'
      - '7072:7071'
    volumes:
      - ./config/kafka2/server.properties:/opt/kafka/config/server.properties
      - ./config/kafka2/kafka-metrics.yml:/opt/jmx_exporter/kafka-metrics.yml
      - ./logs/kafka_data/kafka2/:/opt/kafka/logs
      - ./logs/kafka_data/kafka2/metadata/:/data/kafka
    networks:
      dahbest:
        ipv4_address: 172.80.0.12

  kafka3:
    container_name: kafka3
    build:
      context: ./images/kafka/.
      dockerfile: Dockerfile
    ports:
      - '39092:39092'
      - '7073:7071'
    volumes:
      - ./config/kafka3/server.properties:/opt/kafka/config/server.properties
      - ./config/kafka3/kafka-metrics.yml:/opt/jmx_exporter/kafka-metrics.yml      
      - ./logs/kafka_data/kafka3/:/opt/kafka/logs
      - ./logs/kafka_data/kafka3/metadata/:/data/kafka
    networks:
      dahbest:
        ipv4_address: 172.80.0.13

  debezium:
    hostname: debezium
    container_name: debezium
    build:
      context: ./images/debezium
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
      - "9090:8080"
    volumes:
      - ./config/debezium/connect-metrics.yml:/opt/jmx_exporter/connect-metrics.yml
      - ./config/debezium/connect-distributed.properties:/opt/kafka/config/connect-distributed.properties
      - ./logs/debezium_data:/data/kafka-connect
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - postgres
    networks:
      dahbest:
        ipv4_address: 172.80.0.15

  kafka-ui:
    container_name: kafka-ui
    build:
      context: ./images/provectus/.
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./config/provectus/config.yml:/opt/kafka-ui/config.yml
    networks:
      dahbest:
        ipv4_address: 172.80.0.16
    depends_on:
      - kafka1
      - kafka2
      - kafka3

  postgres:
      image: postgres:16
      container_name: postgres
      environment:
        POSTGRES_USER: cagri
        POSTGRES_PASSWORD: 3541
        POSTGRES_DB: postgres
      ports:
        - "5432:5432"
      volumes:
        - ./logs/postgres-data:/var/lib/postgresql/data
      networks:
        dahbest:
          ipv4_address: 172.80.0.20
      command: ["postgres", "-c", "wal_level=logical", "-c", "max_wal_senders=10", "-c", "max_replication_slots=10"]   
         
networks:
  dahbest:
    external: true