global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: "kafka"
    static_configs:
      - targets:
          - 'kafka1:7071'
          - 'kafka2:7071'
          - 'kafka3:7071'
        labels:
          service: 'kafka'
    metrics_path: /metrics
    scheme: http

  - job_name: 'kafka_exporter'
    static_configs:
      - targets: ['kafka1:9308']
        labels:
          instance: 'kafka'

  - job_name: 'jenkins'
    static_configs:
      - targets:
          - 'jenkins:8080'
        labels:
          service: 'jenkins'
    metrics_path: /prometheus
    scheme: http
    basic_auth:
      username: cagri
      password: '35413541'