global:
  scrape_interval: 15s
  evaluation_interval: 15s
  # Add scrape timeout
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets:
          - 'kafka1:7071'
          - 'kafka2:7071'
          - 'kafka3:7071'
    # Add relabeling to handle time synchronization
    relabel_configs:
      - source_labels: [__name__]
        regex: '^.*$'
        action: keep

  - job_name: 'prometheus'
    static_configs:
      - targets:
          - 'localhost:9090'