kafka:
  clusters:
    - name: cagri_cluster
      bootstrapServers: broker1:9092,broker2:9092,broker3:9092
      properties:
        security.protocol: SASL_SSL
        sasl.mechanism: SCRAM-SHA-256
        sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="kafkaui" password="cagri3541";
        ssl.truststore.location: /opt/jks/kafka-ui.truststore.jks
        ssl.truststore.password: cagri3541

server:
  port: 8080

logging:
  level:
    root: INFO