kafka:
  clusters:
    - name: cagri_cluster
      bootstrapServers: kafka1:9092,kafka2:9092,kafka3:9092
      ksqldbServer: http://ksqldb:8088
      
server:
  port: 8080

logging:
  level:
    root: INFO